services:
  postgres:
    image: postgres:16.3
    container_name: knexdemo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knexdemo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: